### PR TITLE
Rebuild Cython 3.0.0a11 for PyPy3.8, PyPy3.9 and python311

### PR DESCRIPTION
**Pull request by dofuuz**
…ForgeAutomergeUpdate
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by dofuuz** [comment]
@conda-forge-admin, please rerender

**Comment by ocefpaf** [comment]
@dofuuz it may be worth adding the dev branch to the bot migration in the, something like this:

https://github.com/conda-forge/boost-feedstock/blob/fc72cb426ca718cab735a5944c6926a49130ceee/conda-forge.yml#L1-L3

It will save you from sending PRs like this in the future.

**Comment by ocefpaf** [comment]
Actually, it was already done! And the PRs were issued! Missed that entirely.

**Comment by jakirkham** [comment]
Yeah noticed this PR and thought we should get all of the migrations here (in case others are missing). So sent PR ( https://github.com/conda-forge/cython-feedstock/pull/101 ) to get that started. Looks like many of the other migrations were done long ago (before the `dev` branch was created)

**Pull request merged**
