### PR TITLE
Add create_extension hook

### LINKED ISSUE #16: Patch for adding create_extension() hook
https://github.com/cython/cython/pull/466 was recently merged and is needed for building sagemath on osx.

Shall I send a PR that uses this patch?

### PR DESCRIPTION
**Pull request by saraedum**
This is already in master and will allow us to build sagelib-8.0.

This fixes #16.

### CODE REVIEW

**Comment by jakirkham** [comment]
Does anyone know the timeline for the next Cython release? It seems like they haven't had a release in like 6 months, which is atypically long. If we don't know the answer to this question, could you please ask them?

**Comment by saraedum** [comment]
I asked on cython-devel if there are any plans for a release.

**Comment by jakirkham** [comment]
Thank you. Is there a link to mailing list thread or issue so others can follow along?

**Comment by saraedum** [comment]
It's still awaiting moderation. I'll post a link here once it's through.

**Comment by saraedum** [comment]
My message did not show up in their archives. Anyway, @robertwb wrote
```
I've been wanting to do a release for a while, just haven't gotten
around to it. Yes, let's get one out soon.
```

**Comment by isuruf** [comment]
Link is here, https://mail.python.org/pipermail/cython-devel/2017-June/005000.html

**Comment by jakirkham** [comment]
The 0.26 release is being built, which should already include this fix.

**Pull request closed without merging**
