### PR TITLE
Add a pure python variant

### PR DESCRIPTION
**Pull request by isuruf**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

This is useful for new python versions and variants to experiment with.

### CODE REVIEW

**Comment by isuruf** [comment]
@conda-forge-admin, rerender

**Comment by isuruf** [comment]
@conda-forge/cython, thoughts on this? This would be useful to use cython when a new python implementation like freethreading or new python version hasn't been migrated yet.

**Comment by h-vetinari** [comment]
I'm not against it, though I'd prefer to do this by simply copying the right [migrator](https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/main/recipe/migrations/python313t.yaml) - given that it already exists, that is enough to populate the builds.

I understand that noarch builds would be advantageous in more situations than the 3.13-nogil migration, but so far this seems like the first time we need this, and with a reasonable alternative. Even more so because we get a permanently red linter check with the noarch approach here (meaning e.g. automerge won't work).

I imagine this is more of an exploratory effort anyway, but for completeness: 3.0.11 isn't yet compatible with 3.13-nogil, that'll only happen in cython 3.1...

**Comment by isuruf** [comment]
> I understand that noarch builds would be advantageous in more situations than the 3.13-nogil migration, but so far this seems like the first time we need this, and with a reasonable alternative. 

Sure, we do have an alternative, but I am going the same route as the pre-built wheels where specific wheels are built for each popular platform and a noarch wheel is there for the other platforms. This is going to help in the future as well, that's why I sent this PR.

> Even more so because we get a permanently red linter check with the noarch approach here (meaning e.g. automerge won't work).

Yeah, I can introduce a feature to conda-smithy to ignore a warning. Is that the only concern?

**Comment by h-vetinari** [comment]
I'm fine with it here. If you want to introduce it to multiple feedstocks, we should teach the linter not to complain

**Comment by isuruf** [comment]
Thanks

**Pull request merged**
