### PR TITLE
cython 0.29.31

### PR DESCRIPTION
**Pull request by h-vetinari**
Not sure what the bot is stuck on again, but this release has been much-awaited, so let's build it.

Also proposing to add myself to maintainers here, if no-one objects.

### CODE REVIEW

**Comment by jakirkham** [comment]
From [CI]( https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=542608&view=logs&jobId=d0d954b5-f111-5dc4-4d76-03b6c9d0cf7e&j=d0d954b5-f111-5dc4-4d76-03b6c9d0cf7e&t=841356e0-85bb-57d8-dbbc-852e683d1642 ) looks like the `sdist` can't be downloaded (likely the same reason the bot hasn't issued a PR)

```
An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
WARNING:conda_build.source:Error: HTTP 404 NOT FOUND for url <[https://pypi.io/packages/source/C/Cython/Cython-0.29.31.tar.gz>](https://pypi.io/packages/source/C/Cython/Cython-0.29.31.tar.gz%3E)
Elapsed: 00:00.280736
```

Looks similar to other PyPI CDN issues we've seen recently ( https://github.com/pypi/warehouse/issues/11934 ). It is worth noting these are getting fixed, but this maybe an edge case (perhaps due to the capitalization).

**Comment by h-vetinari** [comment]
@jakirkham 
Seems we saw the same error but chose to follow different approaches to tackle it. 🙃 

I tend to prefer GH sources in most cases, not least because it's faster & more direct, but because it also removes a potential injection vector through sources on PyPI being different than on github (not that any of the big packages are at serious risk there, but still...)

From that POV, this PR should be ready.

PS. I'd be very thankful if you could have a quick look at my PR on the openssl feedstock, if you have a moment. :)

**Comment by ocefpaf** [comment]
I'm also +1 for GH sources but, python packaging is such a mess, that in some cases the "injection" is official and there are missing parts in teh GH tarball. This is not the case I'm OK with the changes here. If we have one more +1 we can merge it.

**Comment by jakirkham** [comment]
Appreciate the effort Axel.

It appears PyPI has resolved this issue. Recently the bot came by and added PR ( https://github.com/conda-forge/cython-feedstock/pull/95 ), which seems to work and has been merged.

**Comment by h-vetinari** [comment]
> Appreciate the effort Axel.

Then why merge that other PR? This one was technically superior, faster, and would have added a maintainer (me). I don't assume it was intentional, but it certainly doesn't give me a warm and fuzzy feeling about (re)trying to join this feedstock.

**Pull request closed without merging**
