### PR TITLE
Add dev channel_target for alpha releases (2)

### PR DESCRIPTION
**Pull request by tlambert03**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by tlambert03** [comment]
@conda-forge-admin, please rerender

**Comment by tlambert03** [comment]
Looks like things might be passing.  I'll note, I did remove the pypy patch after seeing the failures in https://github.com/conda-forge/cython-feedstock/runs/5187458969 ...
being a dev channel release, I'm hoping it would be ok to merge this as is, and work on supporting older versions of pypy in a future PR?

**Comment by ocefpaf** [comment]
Do you want to add yourself as a maintainer here before we merge this one?

**Comment by tlambert03** [comment]
sure, added.  thanks!

**Pull request merged**
