### PR TITLE
Update to 0.27.1

### PR DESCRIPTION
**Pull request by isuruf**

### CODE REVIEW

**Comment by isuruf** [comment]
@conda-forge-admin, please lint.
cc @jakirkham, more linter failures

**Comment by jakirkham** [comment]
Was there anything useful in the Heroku logs?

**Comment by isuruf** [comment]
Created https://github.com/conda-forge/conda-forge-webservices/issues/126

**Comment by jakirkham** [comment]
Ah ok. Thanks.

**Comment by jakirkham** [comment]
Thanks @isuruf.

**Pull request merged**
