### PR TITLE
Bump to version 0.25

### PR DESCRIPTION
**Pull request by synapticarbors**
This bumps Cython to 0.25 and includes re-rendering the feedstock

### CODE REVIEW

**Comment by jakirkham** [comment]
Please feel free to add yourself as a maintainer if you wish @synapticarbors . :smile:

**Comment by synapticarbors** [comment]
It appears as if a number of projects are having issues with this release, so let's hold off on this for now.

**Comment by jakirkham** [comment]
Any references?

**Comment by synapticarbors** [comment]
This one is the big one. It's closed and assigned to the 0.25.1 milestone

https://github.com/cython/cython/issues/1496

**Comment by jakirkham** [comment]
Ok, so should we close this then or would you rather update this PR for `0.25.1` when it comes out?

**Comment by synapticarbors** [comment]
I'll just update this PR when the next release comes out.

**Comment by synapticarbors** [comment]
Superseded by #8

**Pull request closed without merging**
